apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lz0yiz97v-nodejs 
  janus-idp.io/tekton: lz0yiz97v-nodejs
  backstage.io/kubernetes-id: lz0yiz97v-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lz0yiz97v-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml